compila: 
	$(CC) main.c skip_list.c -o prova
	$(CC) test.c skip_list.c unity.c -o prova

run:
	./prova "/home/daniela/Documenti/Es2-Algo/Test/dictionary.txt" "/home/daniela/Documenti/Es2-Algo/Test/correctme.txt"
	./prova 
